highlight:
  anchorLineNos: false
  codeFences: true
  guessSyntax: true
  hl_Lines: ""
  hl_inline: false
  lineAnchors: ""
  lineNoStart: 1
  lineNos: false
  lineNumbersInTable: true
  noClasses: false
  noHl: false
  style: github
  tabWidth: 4

goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    linkifyProtocol: https
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    attribute:
      block: false
      title: true
    autoHeadingID: true
    autoHeadingIDType: github
  renderer:
    hardWraps: false
    unsafe: true
    xhtml: false